services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: paster
      POSTGRES_PASSWORD: wficUV6L3xZTj17g2eSafJLjpyL9UdzN
      POSTGRES_DB: flower_6tst
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_app

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://paster:wficUV6L3xZTj17g2eSafJLjpyL9UdzN@dpg-d3k1bgnfte5s73bvgdk0-a.oregon-postgres.render.com/flower_6tst
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pgdata:
